import { getApps, initializeApp } from 'firebase-admin/app';
import { onCall } from 'firebase-functions/v2/https';
import * as adminWorkflow from './admin-workflow.js';
import * as migration from './migration.js';
import * as restore from './restore.js';

if (!getApps().length) initializeApp();
const callable = (handler) => onCall({ region: 'asia-northeast3' }, handler);

export const createRecorderAccessCode = callable(adminWorkflow.createRecorderAccessCode);
export const revokeRecorderAccessCode = callable(adminWorkflow.revokeRecorderAccessCode);
export const listRecorderGrants = callable(adminWorkflow.listRecorderGrants);
export const revokeRecorderGrant = callable(adminWorkflow.revokeRecorderGrant);
export const prepareTournamentReset = callable(adminWorkflow.prepareTournamentReset);
export const recoverTournamentReset = callable(adminWorkflow.recoverTournamentReset);
export const cancelTournamentReset = callable(adminWorkflow.cancelTournamentReset);
export const resetTournament = callable(adminWorkflow.resetTournament);
export const exchangeRecorderAccessCode = callable(adminWorkflow.exchangeRecorderAccessCode);
export const claimRecorderDraft = callable(adminWorkflow.claimRecorderDraft);
export const saveRecorderDraft = callable(adminWorkflow.saveRecorderDraft);
export const renewRecorderLease = callable(adminWorkflow.renewRecorderLease);
export const replaceCourtWorkflows = callable(adminWorkflow.replaceCourtWorkflows);
export const publishFinalStructure = callable(adminWorkflow.publishFinalStructure);
export const clearFinalStructure = callable(adminWorkflow.clearFinalStructure);
export const mutatePrelimStructure = callable(adminWorkflow.mutatePrelimStructure);
export const resumeRecorderDraft = callable(adminWorkflow.resumeRecorderDraft);
export const cancelRecorderDraft = callable(adminWorkflow.cancelRecorderDraft);
export const submitRecorderDraft = callable(adminWorkflow.submitRecorderDraft);
export const approveScoreReview = callable(adminWorkflow.approveScoreReview);
export const rejectScoreReview = callable(adminWorkflow.rejectScoreReview);
export const directEditOfficialScore = callable(adminWorkflow.directEditOfficialScore);
export const forceReleaseWorkflow = callable(adminWorkflow.forceReleaseWorkflow);
export const previewApprovedCorrection = callable(adminWorkflow.previewApprovedCorrection);
export const applyApprovedCorrection = callable(adminWorkflow.applyApprovedCorrection);
export const createMigrationManifest = callable(migration.createMigrationManifest);
export const applyMigrationManifest = callable(migration.applyMigrationManifest);
export const beginRestore = callable(restore.beginRestore);
export const supersedeRestore = callable(restore.supersedeRestore);
export const resumeRestore = callable(restore.resumeRestore);
export const pruneRestore = callable(restore.pruneRestore);
export const verifyRestore = callable(restore.verifyRestore);
export const promoteRestore = callable(restore.promoteRestore);
export const getServerClock = callable(async () => ({ serverTimeMs: Date.now() }));
export const exportTournamentBackup = callable(restore.exportTournamentBackup);
