import crypto from 'node:crypto';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { HttpsError } from 'firebase-functions/v2/https';
import { TOURNAMENT_ID, assertQueueOwnership, projectQueue } from './workflow-core.js';

const db=()=>getFirestore(); const root=()=>db().collection('tournaments').doc(TOURNAMENT_ID);
async function admin(request){if(request.data?.tournamentId!==TOURNAMENT_ID) throw new HttpsError('invalid-argument','Unknown tournament.'); if(!request.auth?.uid) throw new HttpsError('unauthenticated','Authentication required.'); if(!(await root().collection('admins').doc(request.auth.uid).get()).exists) throw new HttpsError('permission-denied','Seeded administrator required.'); return request.auth.uid;}
function canonical(value){if(Array.isArray(value)) return value.map(canonical); if(value&&typeof value==='object') return Object.fromEntries(Object.keys(value).sort().map((key)=>[key,canonical(value[key])])); return value;}
function checksum(value){return crypto.createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}
function safePath(path){return typeof path==='string' && !/(^|\/)(admins|recorderGrants|recorderAccess)(\/|$)/.test(path) && path.startsWith(`tournaments/${TOURNAMENT_ID}/`);}
export async function beginRestore(request){const uid=await admin(request); const {manifestId,chunks=[]}=request.data; if(typeof manifestId!=='string'||!manifestId||!Array.isArray(chunks)) throw new HttpsError('invalid-argument','manifestId and chunks required.'); const manifest=root().collection('restoreManifests').doc(manifestId); return db().runTransaction(async(tx)=>{const old=await tx.get(manifest); if(old.exists) return {manifestId,status:old.data().status}; const normalized=chunks.map((chunk,index)=>({index,documents:(chunk.documents||[]).filter((doc)=>safePath(doc.path)).map((doc)=>({path:doc.path,data:canonical(doc.data)}))})); tx.create(manifest,{manifestId,status:'staged',chunks:normalized.map((chunk)=>({index:chunk.index,checksum:checksum(chunk.documents),count:chunk.documents.length})),createdBy:uid,createdAt:FieldValue.serverTimestamp()}); normalized.forEach((chunk)=>tx.create(manifest.collection('chunks').doc(String(chunk.index)),chunk)); tx.set(root(),{maintenance:{enabled:true,restoreManifestId:manifestId}}, {merge:true}); return {manifestId,status:'staged'};});}
export async function resumeRestore(request){await admin(request); const {manifestId,chunkIndex}=request.data; const manifest=root().collection('restoreManifests').doc(manifestId); return db().runTransaction(async(tx)=>{const [meta,chunk]=await Promise.all([tx.get(manifest),tx.get(manifest.collection('chunks').doc(String(chunkIndex)))]); if(!meta.exists||!chunk.exists) throw new HttpsError('not-found','Restore chunk not found.'); if(meta.data().status==='promoted') return {manifestId,chunkIndex,applied:true}; const expected=meta.data().chunks.find((item)=>item.index===chunkIndex); if(!expected||expected.checksum!==checksum(chunk.data().documents)) throw new HttpsError('failed-precondition','Checksum mismatch.'); for(const item of chunk.data().documents){if(!safePath(item.path)) continue; tx.set(db().doc(item.path),item.data);} tx.set(chunk.ref,{appliedAt:FieldValue.serverTimestamp()},{merge:true}); tx.set(manifest,{status:'restoring'},{merge:true}); return {manifestId,chunkIndex,applied:true};});}
export async function verifyRestore(request){await admin(request); const manifest=root().collection('restoreManifests').doc(request.data?.manifestId); const [meta,chunks]=await Promise.all([manifest.get(),manifest.collection('chunks').get()]); if(!meta.exists) throw new HttpsError('not-found','Restore manifest not found.'); const checks=meta.data().chunks; const complete=checks.length===chunks.docs.length&&chunks.docs.every((snap)=>snap.data().appliedAt); if(!complete) throw new HttpsError('failed-precondition','All chunks must be applied.'); const queues=await root().collection('courtQueues').get(); for(const queue of queues.docs){const assignments=await root().collection('courtAssignments').where('courtId','==',queue.id).get(); const assignmentMap=Object.fromEntries(assignments.docs.map((snap)=>[snap.id,snap.data()])); const workflows=await Promise.all(assignments.docs.map((snap)=>root().collection('scoreWorkflows').doc(snap.id).get())); const workflowMap=Object.fromEntries(workflows.map((snap)=>[snap.id,snap.exists?snap.data():{}])); assertQueueOwnership(queue.data(),assignmentMap,workflowMap); const projected=projectQueue(queue.data(),assignmentMap,workflowMap); if(projected.currentMatchKey!==queue.data().currentMatchKey||projected.nextMatchKey!==queue.data().nextMatchKey) throw new HttpsError('failed-precondition','Queue v3 invariants failed.'); } await manifest.set({status:'verified',verifiedAt:FieldValue.serverTimestamp()},{merge:true}); return {manifestId:meta.id,verified:true};}
export async function promoteRestore(request){await admin(request); const manifest=root().collection('restoreManifests').doc(request.data?.manifestId); return db().runTransaction(async(tx)=>{const snap=await tx.get(manifest); if(!snap.exists) throw new HttpsError('not-found','Restore manifest not found.'); if(snap.data().status==='promoted') return {manifestId:snap.id,promoted:true}; if(snap.data().status!=='verified') throw new HttpsError('failed-precondition','Restore must be verified first.'); tx.update(snap.ref,{status:'promoted',promotedAt:FieldValue.serverTimestamp()}); tx.set(root(),{maintenance:{enabled:false,restoreManifestId:null}},{merge:true}); return {manifestId:snap.id,promoted:true};});}
